#!/usr/bin/env python3
#CODED BY WYATT BECKER
#-------------------------------------------------------------------------------
# In this example, test.txt contains the numbers 1-5 each seperated by a '\n'
#-------------------------------------------------------------------------------
# Usage with file:            # Usage with specified integer    # Usage with line count from file
# 4loop 'echo LINE' test.txt    4loop 'echo hello world' 5        4loop 'echo foo' test.txt
# output:                       output:                           output:
# 1                             hello world                       foo
# 2                             hello world                       foo
# 3                             hello world                       foo
# 4                             hello world                       foo
# 5                             hello world                       foo

# This program is especially useful with scope files ;)
# 4loop 'nmap LINE' scope.txt

# TODO: Switch sys.argv[1] and sys.argv[2] around to permit some commands without ''

import sys
import os
from time import sleep

def print_help():
    print("SYNTAX: 4loop '[command]' [iterations or filename]")
    print("Use 'LINE' as variable for line in file")
    print()
    exit()

try: # Try to set global variables
    command=str(sys.argv[1])    # String we'll use as the command to execute
    iterations=sys.argv[2]      # how many repeats
except:
    print_help()

# Checks if arg2 is a file or not and choosees iterations accordingly
def looper(command,iterations):
    if not iterations.isdigit():# if it's not a digit assume its string
        iterations=str(iterations)
        if os.path.exists(iterations): # Check if filename exists
            file=iterations # So we can use iterations as a diff variable while keeping filename
            iterations = sum(1 for line in open(file)) # iters = number of lines in file
            if "LINE" in command: # Give option to use line in file rather than just iter count
                    for line in open(file):
                        try:
                            new_cmd=command.replace("LINE", line.rstrip()) # Replace "LINE" with the line from filew
                            os.system(new_cmd)
                            sleep(.031) #slowed down in order to break out of loop (needs fine tuning)
                        except KeyboardInterrupt:
                            return
            else: # Else just do command as many times as there are lines in the specified file.
                for i in range(0,iterations):
                    os.system(command)
        else:
            print()
            print("You entered a filename that doesn't exist...")
            print()
            sleep(1) # Asthetics
            print_help()
    else: # Else do command as many times as the specified int
        iterations=int(iterations)
        for i in range(0,iterations):
            os.system(command)

looper(command,iterations)
